---
title: "makeShift"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{makeShift}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(actR)
```

### Build a synthetic time series with a shift in mean

The time series will have 100 time steps, with a shift in mean at time 20

The mean shift will have a magnitude of 0.5

```{r}
syntheticTransition <- makeShift(length = 300, amp=0.5, start = 65)
```

### Detect Shift

we will test the synthetic time series with `detectShift`

```{r}
synTrans <- detectShift(syntheticTransition,
                     time.variable.name = "year",
                     null.hypothesis.n = 50,
                     summary.bin.step = 1,
                     minimum.segment.length = 50,
                     simulate.time.uncertainty = FALSE,
                     method = "AMOC",
                     cpt.fun = changepoint::cpt.mean,
                     paleo.uncertainty = 0.1,
                     n.ens = 50)
```


###Plot shift

Let's plot the results

```{r}

plotShift(synTrans)

```
