---
title: "mapping_excursions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mapping_excursions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
  knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  )
```
  
```{r setup}
  library(actR)
  library(lipdR)
  library(dplyr)
  library(purrr)
```
  
  
  
```{r}
#Get some data from the 4.2 paper
googlesheets4::gs4_deauth()
sites <- googlesheets4::read_sheet("1ReehV_sHCOwMalaFE_5NJyANEPih_nT0tBIQO1IeHak")

#download the corresponding data
northAtlanticData <- readLipd(sites$datasetId)

#create a timeseries tibble
nats <- as.lipdTsTibble(northAtlanticData)

#filter down to just the data we want
filtNats <- nats |> 
filter(paleoData_TSid %in% sites$paleoData_TSid)

```



```{r}
#look for the 8.2 ka event at these sites:

tp <- split(filtNats,seq(nrow(filtNats)))


test <- detectExcursion(tp[[1]],
                  event.yr = 8200,
                  event.window = rnorm(50,400,100),
                  ref.window = rnorm(50,400,100),
                  exc.type = "negative",
                  n.ens = 50,
                  sig.num = rnorm(50,2,.1),
                  n.consecutive = sample(c(2,3,4),size = 50,replace = TRUE),
                  null.hypothesis.n = 50,
                  simulate.time.uncertainty = FALSE,
                  simulate.paleo.uncertainty = TRUE,
                  paleo.uncertainty = 0.2,
                  min.vals = 4,
                  paleo.ar1 = 0.8)

events8.2 <- purrr::map(tp,
                  detectExcursion,
                  event.yr = 8200,
                  event.window = rnorm(50,400,100),
                  ref.window = rnorm(50,400,100),
                  exc.type = "negative",
                  n.ens = 50,
                  sig.num = rnorm(50,2,.1),
                  n.consecutive = sample(c(2,3,4),size = 50,replace = TRUE),
                  null.hypothesis.n = 50,
                  simulate.time.uncertainty = FALSE,
                  simulate.paleo.uncertainty = TRUE,
                  paleo.uncertainty = 0.2,
                  min.vals = 4,
                  paleo.ar1 = 0.8,
                  .progress = TRUE) |> 
  purrr::list_rbind() |> 
  dplyr::filter(!is.na(pvalue))

```


```{r}

lon.range <- range(events8.2$geo_longitude) + c(-5,5)
lat.range <- range(events8.2$geo_latitude) + c(-5,5)

dist.grid <- distanceGrid(events8.2,lon.range = lon.range,lat.range = lat.range,grid.resolution = 3)


pval.grid.weight.temp <- map(dist.grid,
                             spatialSigTest,
                             events=events8.2,
                             agg.method="robustNull",
                             use.weights = TRUE,
                             distance.cutoff = 1000,
                             .progress = TRUE)


```
make a map!

```{r}
    figoutTemp <- plotSignificance(pval.grid.weight.temp,
                                   sigTestResults = events8.2,
                               which.test = "pvalNeg",
                               color.breaks = c(0.01,0.05,0.1,0.2),
                               restrict.sites = TRUE,
                               alpha.by.weight = TRUE,
                               cutoff.distance = 1000,
                               x.lim = lon.range,
                               y.lim = lat.range)

figoutTemp$plot
```

