---
title: "neotoma"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{neotoma}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(actR)
# library(neotoma)
# library(neotoma2lipd)
# library(lipdR)
# library(tidyverse)
# library(geoChronR)
```

```{r}
# site <- neotoma::get_site("Penegor Lake")
# L <- neotoma2Lipd(site)
```

```{r}
# neg <- which(L$chronData[[1]]$measurementTable[[1]]$age$values < 0)
# 
# 
# if(length(neg) > 0){
#   L$chronData[[1]]$measurementTable[[1]]$age$values[neg] <- NA
# }
# 
# L <- runBacon(L,chron.num = 1,bacon.dir = "~/Cores",model.num = 2,lab.id.var = NULL, age.14c.var = 'age', age.14c.uncertainty.var = 'unc.estimate', age.var = NULL, age.uncertainty.var = NULL, depth.var = 'depth', reservoir.age.14c.var = NULL, reservoir.age.14c.uncertainty.var = NULL, rejected.ages.var = NULL,ask = FALSE, suggest = FALSE)


```



```{r}

```



